spring:
  profiles:
    active: dev

fastdfs:
  upload-fail-ignore: true
  connectTimeout: PT5S
  soTimeout: PT15S
  charset: UTF-8
  pool:
    max-total: 200
    max-wait-millis: 500
  cluster:
    nodes:
      - 10.0.75.2:22122
