spring.profiles.active: dev

fastdfs:
  connectTimeout: PT5S
  networkTimeout: PT5S
  soTimeout: PT15S
  charset: UTF-8
  pool:
    maxSize: 10
    minSize: 1
    maxIdleTime: PT5S
    maxAttempt: 3
  cluster:
    nodes:
    - 10.138.30.97:22122
#    - 10.138.30.40:22122
#    - 10.138.30.42:22122